sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.2

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8

install: true

script:
  - java -version
  - sbt test

branches:
  only:
    - master
    - develop

# Work around for default old version of Java provided by Travis CI
addons:
  apt:
    packages:
      - oracle-java8-installer