sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.2

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk11

install: true

script:
  - java -version
  - sbt test

branches:
  only:
    - master
    - develop
