sudo: false
language: scala
scala:
  - 2.12.15
  - 2.13.6

jdk:
  - openjdk11
  - openjdk16

install: true

script:
  - java -version
  - sbt ++$TRAVIS_SCALA_VERSION test

branches:
  only:
    - master
    - release
