name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }} sample

    steps:
    - uses: actions/checkout@v2
    - name: Set Java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: '<distribution>'
        java-version: ${{ matrix.java }}
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: sbt +test
